schema: lib/type-defs.graphqls
documents:
  - '**/*.graphql'
  - '!node_modules/**'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
respectGitIgnore: true
config:
  reactApolloVersion: 3
  apolloReactComponentsImportFrom: '@apollo/client/react/components'
cacheDir: __generated__
